### ISSUE TITLE
数据集疑问

### ISSUE THREAD

**Issue by CreaterLL** [Zhang-xiaokun/MMSBR#1]
您好，看了代码，有以下疑问:
1. 代码中写了这些数据集：'dataset name: Office_Products/Grocery_and_Gourmet_Food/Cell_Phones_and_Accessories/Clothing_Shoes_and_Jewelry/Home_and_Kitchen/sample'，
但是，项目里只有Grocery_and_Gourmet_Food数据集的压缩包，请问其他数据集怎么获取呢，是否有相应代码呢，有的话方便给一个代码执行流程吗？
2，打开数据集连接，发现有很多数据，请问应该下载哪一个数据做实验呢？（raw review data (34gb) - all 233.1 million reviews、ratings only (6.7gb) 、5-core (14.3gb) 和meta data (12gb) - meta data for all products数据集选项）
![image](https://github.com/Zhang-xiaokun/MMSBR/assets/63894612/045d2f3f-58f3-4923-8daa-cfc446f17c98)

希望作者大大能解答一下不，谢谢！

**Comment by Zhang-xiaokun** [comment]
欢迎关注我们的工作~
1. 所有三个预处理好的数据已经上传，直接运行即可，另外，所有预处理的代码也已经公开，你可以用其处理自己的数据；
2. Amazon的数据集描述很详细，你可以按照自己的需求选取合适的数据集，我们方法里: 从5-core的数据获取user-item交互信息(文件名如 Cell_Phones_and_Accessories_5.json.gz)；meta数据里获取item的信息如图片，文本，价格（文件名如 meta_Cell_Phones_and_Accessories.json.gz）。

**Comment by CreaterLL** [comment]
谢谢作者大大回复，明白了！
