### ISSUE TITLE
结果疑问

### ISSUE THREAD

**Issue by CreaterLL** [Zhang-xiaokun/MMSBR#2]
您好，跑了您的代码，对于代码输出结果有一些疑问：
![image](https://github.com/Zhang-xiaokun/MMSBR/assets/63894612/5febcc70-d6e7-4691-b895-6e42760fe30d)
图中的指标该怎么看呢，比如：图中'mrr20': 34.89601843675812与下面的 M@20对应的两个数字36.05和16（如下图）
![image](https://github.com/Zhang-xiaokun/MMSBR/assets/63894612/5991da0e-8d04-48d4-b10a-cbd822e3d12e)
有什么关系呢？

**Comment by Zhang-xiaokun** [comment]
欢迎关注我们的工作~
第一行是对应指标的实验结果，第二行是该结果出现的epoch

**Comment by CreaterLL** [comment]
明白了，感谢您的答复！
