### ISSUE TITLE
超参数疑问

### ISSUE THREAD

**Issue by codeCyw** [Zhang-xiaokun/MMSBR#3]
尊敬的张博士：
        首先，非常感谢您与团队开源这么优秀的工作。近日拜读完MMSBR这篇文章深感佩服，我在跑您的程序时有以下疑惑，希望能得到您的解答。

**Comment by codeCyw** [comment]
(按回车时自动提交了，问题还没有说完，麻烦您继续往下看)
在下载您的代码后，我直接使用python main.py运行了程序，对于main.py文件，我只对--dataset参数的值做出修改，以下是dataset值分别为Cell_Phones_and_Accessories和Grocery_and_Gourmet_Food时的部分结果。
![image](https://github.com/Zhang-xiaokun/MMSBR/assets/65146354/e1ca6f1e-c74d-485a-b837-a9c15e9f269b)

从上图可见，在Grocery_and_Gourmet_Food运行至第12个epoch时，结果已经与您在论文中公布的结果非常接近。而在Cell_Phones_and_Accessories数据集下，运行至第33个epoch仍然与您论文中的结果相去甚远。我想这可能有两个原因：
1. 默认的超参数设置可能更适用于Grocery_and_Gourmet_Food数据集，而对于Cell_Phones_and_Accessories数据集来说，可能需要一些特定的超参数调整。
2. 训练轮数（epochs）设置为默认值100，但也许Cell_Phones_and_Accessories数据集需要更多的训练轮数才能达到论文中的预期性能。


在此背景下，我想向您请教一下：

1. 您是否能提供各个数据集的最佳超参数设置，以便我们更好地重现您在论文中的实验结果？
2. 对于这三个数据集，模型训练达到收敛状态需要多少轮（epochs），每个轮次大致需要多长时间？
3. 您在训练时所使用的GPU型号是什么？

以上是我打算提出的问题，其中问题2 问题3如果您在实验时没有记录请忽略，期待您的回复，非常感谢您的阅读。

此致敬礼

**Comment by Zhang-xiaokun** [comment]
首先，欢迎关注我们的工作~
  关于您提到的几个问题：
1. 各个数据集的最佳超参设置在我们的原文中作了说明，请参见原文 ‘6.7 Hyperparameter Study‘，按照原文给的超参设置，在代码中调节对应的三个超参 R, C, T的值即可；
2. 关于收敛的epoch，模型收敛的还挺快的，一般20个epoch就能达到最优解，我们的做法是常规的early stop，主要观察Prec@20这个指标，5个epoch没有提升的话，就可以提升优化了。（实验时，可以参考结果下面的epoch个数和最上面的 epoch:xx, 可以看出结果有多少个epoch没有再提高了）；
3. 我们实验室的GPU目前有点杂，我使用的GPU也不统一，有2080，3080， 3090，还有4090，都是单卡的，内存12G到24G不等；
4. 关于图1，epoch有点多，我猜测可能是GPU的硬件资源或者其他因素的原因，导致模型需要很多轮才能收敛，我们之前在3080上进行实验的时候也遇到过类似情况。如果差的结果有点多（经验上来说，如跑了10个epoch结果还跟最优结果差别比较大，那可能模型这次训练就有点跑偏了），你可以提前结束，然后重新跑一下，模型在少量epoch下就能收敛了。目前对此现象，还不清楚具体是啥原因。
  再次感谢对我们论文的关注~

**Comment by codeCyw** [comment]
感谢您的指导，您的答复非常详细。这是我阅读的您的第三篇论文，我认为您的工作详实，描述清晰，结果真实可靠，祝您科研顺利，成果多多~
